apiVersion: apps/v1
kind: Deployment
metadata:
  name: edulearn
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: edulearn
  template:
    metadata:
      labels:
        app: edulearn
    spec:
      containers:
      - name: edulearn
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080

